version: '2'
services:
  pg:
    container_name: postgres
    image: postgres:9.5
    volumes:
      - /data/postgres:/var/lib/postgresql/data
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
      - "80:80"
      - "1600:1600"
    volumes:
      - /conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /conf/nginx/sites-enabled:/etc/nginx/sites-enabled
      - /conf/ca:/etc/ca
      - /data/logs:/var/log/nginx
      - /conf/tls/certificates:/etc/nginx/certs
      - /data/html:/var/www/html
      - /data/update:/data/update
